name: automate

on:
  schedule:
    # Run once or twice a day at specific times (free tier friendly)
    - cron: '30 3 * * *'    # 3:30 AM UTC
    - cron: '45 17 * * *'   # 5:45 PM UTC
  workflow_dispatch:  # Keep manual trigger for testing

jobs:
  random-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Setup Git
        run: |
          git config --global user.name "22lavanyas"
          git config --global user.email "22lavanya11@gmail.com"
          
      - name: Create random number of commits
        run: |
          # Generate a random number of commits between 1 and 5
          NUM_COMMITS=$(( $RANDOM % 5 + 1 ))
          
          echo "Creating $NUM_COMMITS random commits"
          
          for (( i=1; i<=$NUM_COMMITS; i++ ))
          do
            # Add random delay between 10-60 seconds between commits
            DELAY=$(( $RANDOM % 50 + 10 ))
            echo "Waiting $DELAY seconds before commit $i"
            sleep $DELAY
            
            # Generate timestamp
            TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
            
            # Create random content
            RANDOM_STRING=$(openssl rand -hex 8)
            echo "$TIMESTAMP - Automated update #$i" >> commit_log.txt
            echo "Random content: $RANDOM_STRING" >> commit_log.txt
            
            # Add and commit
            git add commit_log.txt
            git commit -m "Automated update [$TIMESTAMP] #$i"
          done
          
      - name: Push changes
        run: |
          git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
