name: Noddy Hack

on:
  workflow_dispatch:
  schedule:
    # Run once a day at 00:05 AM UTC
    - cron: '5 0 * * *'
  
jobs:
  create-random-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "22lavanya11@gmail.com"

      - name: Make random number of commits
        run: |
          #!/bin/bash
          set -e

          NUM_COMMITS=$(( ( RANDOM % 34 ) + 2 ))  # 2 to 15 commits
          echo "Number of commits to make: $NUM_COMMITS"

          for ((i=1;i<=NUM_COMMITS;i++)); do
            # Sleep random amount of time between 5 and 60 minutes
            SLEEP_MINUTES=$(( ( RANDOM % 55 ) + 5 ))
            echo "Sleeping for $SLEEP_MINUTES minutes before commit #$i..."
            sleep "${SLEEP_MINUTES}m"

            TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
            RANDOM_STRING=$(openssl rand -hex 8)
            echo "$TIMESTAMP - Commit $i - $RANDOM_STRING" >> commit_log.txt

            git add commit_log.txt
            git commit -m "Automated update #$i [$TIMESTAMP]"
            git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
          done
